baseURL = "https://humaans.github.io/figbird"
languageCode = "en-us"
title = "Figbird"
description = "Effortless realtime data management for React + Feathers applications."

[markup]
  [markup.highlight]
    noClasses = false
    tabWidth = 4
